export const mockBroadcastData = {
  id: "mock-broadcast-id",
  name: "Mock Broadcast",
  status: "active",
  overlay_id: null,
  featured: false,
  top_info_text: "RLCS Season X - Regional 1",
  series_number: 5,
  created_at: "2024-01-01T00:00:00.000Z",
  created_by: null,
  teams: [
    {
      id: "0",
      broadcast_id: "mock-broadcast-id",
      session_id: null,
      organization_id: null,
      color_id: null,
      name: "Blue Team",
      series_score: 2,
      logo: "https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/fit.sidearmsports.com/images/responsive_2021/logo-main.svg",
      side: "blue",
      created_at: "2024-01-01T00:00:00.000Z",
      created_by: null,
      color: {
        id: "color-blue",
        name: "Blue",
        primary_color: "#910000",
        secondary_color: "#ffffff",
        mutual_color: "#000000",
        created_at: "2024-01-01T00:00:00.000Z",
        created_by: null,
      },
    },
    {
      id: "1",
      broadcast_id: "mock-broadcast-id",
      session_id: null,
      organization_id: null,
      color_id: null,
      name: "Orange Team",
      series_score: 1,
      logo: "https://pbs.twimg.com/profile_images/1807909929921269760/wnTKfFoo_400x400.jpg",
      side: "orange",
      created_at: "2024-01-01T00:00:00.000Z",
      created_by: null,
      color: {
        id: "color-orange",
        name: "Orange",
        primary_color: "#106600",
        secondary_color: "#ffffff",
        mutual_color: "#000000",
        created_at: "2024-01-01T00:00:00.000Z",
        created_by: null,
      },
    },
  ],
};
